### ISSUE TITLE
Remote Playback HTTP headers

### ISSUE THREAD

**Issue by pthatcherg** [w3c/openscreenprotocol#146]
What HTTP headers should we recommend go into the Remote Playback start request?

**Comment by pthatcherg** [comment]
In discussion at TPAC, we thought Accept-Language is enough, but maybe CSP.

**Comment by mfoltzgoogle** [comment]
From https://www.w3.org/2019/09/15-webscreens-minutes.html#x15:

> ACTION: mfoltzgoogle to look at CSP-related HTTP headers to pass with remote playback

**Comment by mfoltzgoogle** [comment]
The current protocol allows the agent starting remote playback to send HTTP headers to the agent fetching the resource with the `remote-playback-start-request`.

https://w3c.github.io/openscreenprotocol/#remote-playback-protocol

If we want to require specific headers I believe that is more in scope for the Remote Playback API (since that requirement would apply to any implementation of the API).  Right now there is a NOTE suggesting that `Accept-Language` should be passed.

https://www.w3.org/TR/remote-playback/#establishing-a-connection-with-a-remote-playback-device

I think this can be closed.
