### ISSUE TITLE
Make a required/default remote playback state table

### ISSUE THREAD

**Issue by pthatcherg** [w3c/openscreenprotocol#148]
The remote playback API control protocol text (currently in PR) is a bit verbose explaining what is required in the initial state and what the defaults are when they aren't required.  Having a table would be nice.

**Comment by takumif** [comment]
For the [state](https://webscreens.github.io/openscreenprotocol/#issue-6098c204) fields, we've only said that `source` is required in a `remote-playback-start-response` message. Is `source` required because the request may contain multiple URLs and the receiver must choose one?

Are all the other fields in a `remote-playback-start-response` message optional? For example when we say "The default is empty (support for nothing) for the initial state in the `remote-playback-start-response` message" (for `supports`), do we mean that the message doesn't need to set it, and if not set we'd just assume it's empty?

**Comment by pthatcherg** [comment]
I don't remember why it's required, but that sounds like a good reason :).

Yes, I believe the rest of the fields are optional.

**Comment by mfoltzgoogle** [comment]
It looks like this was done in PR #217 by @takumif (Thank you!)  I looked through the table and nothing looks amiss.

I will clarify why `source` is required in the `remote-playback-start-response` message and close this out.
