### ISSUE TITLE
TPAC October 2020 topics

### ISSUE THREAD

**Issue by rektide** [w3c/openscreenprotocol#244]
Hello. I saw [the secondscreen-wg is having a meeting at the mid-late-October TPAC](https://github.com/w3c/secondscreen-wg/issues/1).

What are some topics openscreenprotocol might bring to that TPAC meeting?

I'm curious what the main concerns are for openscreenprotocol right now. It feels like there is a pretty good basis to work from at this point, although there are numerous outstanding questions/concerns & there will be changes. What would folks like to see, before we start soliciting early implementers / experiments? Very much looking forward to seeing openscreenprotocol in the world; it feels like the shared backbone for our emerging ubiquotous computing capabilities.

**Comment by mfoltzgoogle** [comment]
Because of COVID and other priorities, we (from Chrome) haven't been able to do a lot of work on the spec or implementation over the past 9 months or so. 

Several "v1" issues have pending resolutions from TPAC 2019, and just need pull requests to implement them.

The time at TPAC will likely be updating the group on related work in other groups (Media WG, IETF CFRG) and triaging a selected set of issues that may have more of an impact on the spec and implementation moving forward.

Here are the issues I've flagged for discussion:

- [ ] https://github.com/w3c/openscreenprotocol/issues/242
- [ ] https://github.com/w3c/openscreenprotocol/issues/241
- [ ] https://github.com/w3c/openscreenprotocol/issues/223
- [ ] https://github.com/w3c/openscreenprotocol/issues/194
- [ ] https://github.com/w3c/openscreenprotocol/issues/159

We should also spend a bit of time discussing next steps for the spec as a whole, now that it has been moved into the working group.  (https://github.com/w3c/openscreenprotocol/issues/98)

**Comment by rektide** [comment]
Thank you all ever so much for your work on this wonderful wonderful project.

Open Screen Protocol was the first session at the [secondary screen wg/cg vF2F](https://github.com/w3c/secondscreen-wg/issues/1). Meeting notes are [here](https://www.w3.org/2020/10/20-webscreens-minutes.html#t01).

Again, I really appreciate you bringing some good topics to the group & thanks you @mfoltzgoogle & thank you all again for the amazing work on this groundbreaking work to make the web much wider. Closing this issue, if no objections. Thanks! ⭐ The future is exciting. ⭐
